### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by Tokz** [hendraanggrian/countrypicker#5]
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:19:5-195:19 to override.

**Comment by Tokz** [comment]
fix: https://github.com/android/android-ktx/issues/576

**Comment by hendraanggrian** [comment]
I'm going to guess that you haven't migrated your project to AndroidX yet, which is a requirement for this library.

**Comment by Tokz** [comment]
is it ok to use the above fix?

**Comment by hendraanggrian** [comment]
It may compile, but I doubt it runs without runtime error. I could be wrong, though.

But even if it runs without error, it is inefficient since you are using both Support Libraries and AndroidX Libraries.

I encourage you to migrate to AndroidX, unless you are using some kind of third-party libraries that are still using Support Library, it's best not to use this library altogether. I'd be happy to look at your Gradle build scripts.

**Comment by Tokz** [comment]
I tried the fix but cause a lot of errors and migrating to AndroidX is not an option.

its a good library thought.

Thanks.
